In [1]:
import numpy as np

rev_q1 = np.array([10,12,9])
rev_q1.ndim

1

In [8]:
rev = np.array([[10,12,9],[15,11,13]], dtype=np.float64)
rev.dtype
rev.ndim


2

In [3]:
rev

array([[10, 12,  9],
       [15, 11, 13]])

In [10]:
rev.itemsize

8

In [11]:
rev.size

6

In [12]:
rev.shape

(2, 3)

In [14]:
np.sort(rev,axis=None)

array([ 9., 10., 11., 12., 13., 15.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.arange(20,30,2)

array([20, 22, 24, 26, 28])

In [22]:
np.linspace(10,20,num=5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [23]:
rev

array([[10., 12.,  9.],
       [15., 11., 13.]])

In [25]:
rev.ravel()

array([10., 12.,  9., 15., 11., 13.])

In [26]:
rev.flatten()

array([10., 12.,  9., 15., 11., 13.])

In [27]:
rev.shape

(2, 3)

In [28]:
rev.reshape(3,2)

array([[10., 12.],
       [ 9., 15.],
       [11., 13.]])

In [29]:
rev.min()

np.float64(9.0)

In [30]:
rev.max()

np.float64(15.0)

In [31]:
print(rev.max())

15.0


In [33]:
rev.sum(axis=1)

array([31., 39.])

In [34]:
for row in rev:
    print("row -> ",row)

row ->  [10. 12.  9.]
row ->  [15. 11. 13.]


In [35]:
b = np.array([1,4,16])

In [37]:
np.square(b)

array([  1,  16, 256])

In [38]:
np.sqrt(b)

array([1., 2., 4.])

In [39]:
np.std(b)

np.float64(6.48074069840786)