In [1]:
import numpy as np

In [5]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [7]:
python_list = list(range(100))
python_list[:5]

[0, 1, 2, 3, 4]

In [10]:
import sys

sys.getsizeof(python_list[0])*len(python_list)

2800

In [11]:
numpy_array = np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [12]:
numpy_array.nbytes

800

In [14]:
size = 100000

l1 = list(range(size))
l2 = list(range(size))

l1[:5]
l2[:5]

[0, 1, 2, 3, 4]

In [21]:
import time

start_time = time.time()
l3 = [x+y for x,y in zip(l1,l2)]
end_time = time.time()

print("Python list took: ",end_time-start_time)

Python list took:  0.019503116607666016


In [19]:
n1 = np.arange(size)
n2 = np.arange(size)
n1[:5]

array([0, 1, 2, 3, 4])

In [23]:
start_time = time.time()
n3 = n1 + n2
end_time = time.time()

print("Numpy array took: ",end_time-start_time)
n3[:5]

Numpy array took:  0.0


array([0, 2, 4, 6, 8])