In [1]:
import numpy as np

In [10]:
a = np.array([1,2,3,4,5,6])

In [11]:
a

array([1, 2, 3, 4, 5, 6])

In [5]:
a[:3]

array([1, 2, 3])

In [9]:
a[-1]

np.int64(6)

In [12]:
a[2:4]

array([3, 4])

In [13]:
b = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
b[1,2]

np.int64(6)

In [15]:
b[1,0:2]

array([4, 5])

In [16]:
c = np.array([
    [101, 'Mira'],
    [102, 'Abdul'],
    [103, 'Andrea']
])
# Customer Id, Purchase Amount, Purchase Date
d = np.array([
    [101, 250.50, '2023-08-01'],
    [102, 150.00, '2023-08-02'],
    [103, 300.75, '2023-08-01']
])

c

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [18]:
np.hstack((c,d))

array([['101', 'Mira', '101', '250.5', '2023-08-01'],
       ['102', 'Abdul', '102', '150.0', '2023-08-02'],
       ['103', 'Andrea', '103', '300.75', '2023-08-01']], dtype='<U32')

In [19]:
c


array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea']], dtype='<U21')

In [20]:
e = np.array([
    [104, 'Venkat'],
    [105, 'John'],
    [106, 'Kathy'],
])
e

array([['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [21]:
np.vstack((c,e))

array([['101', 'Mira'],
       ['102', 'Abdul'],
       ['103', 'Andrea'],
       ['104', 'Venkat'],
       ['105', 'John'],
       ['106', 'Kathy']], dtype='<U21')

In [22]:
transactions = np.array([
    [101, 'Mohan', 250.50, '2023-08-01'],
    [102, 'Bob', 150.00, '2023-08-02'],
    [103, 'Fatima', 300.75, '2023-08-01'],
    [104, 'David', 400.20, '2023-08-03'],
    [105, 'Aryan', 330.1, '2023-08-04'],
])
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [33]:
a,b=np.hsplit(transactions,[2])
a

array([['101', 'Mohan'],
       ['102', 'Bob'],
       ['103', 'Fatima'],
       ['104', 'David'],
       ['105', 'Aryan']], dtype='<U32')

In [34]:
b

array([['250.5', '2023-08-01'],
       ['150.0', '2023-08-02'],
       ['300.75', '2023-08-01'],
       ['400.2', '2023-08-03'],
       ['330.1', '2023-08-04']], dtype='<U32')

In [36]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [38]:
x,y=np.vsplit(transactions,[3])
x

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01']], dtype='<U32')

In [39]:
y

array([['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [40]:
monthy_sales = np.array([30,33,35,38,42])

results = monthy_sales > 32
results

array([False,  True,  True,  True,  True])

In [41]:
monthy_sales[results]

array([33, 35, 38, 42])

In [42]:
monthy_sales.max()

np.int64(42)

In [44]:
index = np.argmax(monthy_sales)
index

np.int64(4)

In [45]:
monthy_sales[4]

np.int64(42)

In [47]:
transactions

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')

In [53]:
transactions[:,2].astype(float)

array([250.5 , 150.  , 300.75, 400.2 , 330.1 ])

In [55]:
t_index = np.argmax(transactions[:,2].astype(float))
t_index

np.int64(3)

In [56]:
transactions[t_index]

array(['104', 'David', '400.2', '2023-08-03'], dtype='<U32')

In [57]:
transactions[:]

array([['101', 'Mohan', '250.5', '2023-08-01'],
       ['102', 'Bob', '150.0', '2023-08-02'],
       ['103', 'Fatima', '300.75', '2023-08-01'],
       ['104', 'David', '400.2', '2023-08-03'],
       ['105', 'Aryan', '330.1', '2023-08-04']], dtype='<U32')